version: "3"

services:
  # Selenium Hub to control browsers
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - 4444:4444
    extra_hosts:
      - "owasp-vwa:192.168.60.128"

  # Chrome node for Functional Testing
  chrome:
    image: selenium/node-chrome-debug:latest
    container_name: chrome-node
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5900:5900
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    extra_hosts:
      - "owasp-vwa:192.168.60.128"

  # Firefox node for Functional Testing
  firefox:
    image: selenium/node-firefox-debug:latest
    container_name: firefox-node
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5901:5900
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    extra_hosts:
      - "owasp-vwa:192.168.60.128"

  # ZAP 2.9.0 for Security Testing
  zap:
    image: owasp/zap2docker-stable:2.9.0
    container_name: zap
    command: zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    ports:
      - 8090:8090
    expose:
      # ZAP is running on 8090, we want it to be accessible by our tools
      - 8090
    extra_hosts:
      - "owasp-vwa:192.168.60.128"

  # DVWA (Damn Vulnerable Web Application) as a target app
  web-dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: web-dvwa
    ports:
      - 80:80

  # BodgeIt Store as a target app
  bodgeit:
    image: psiinon/bodgeit:latest
    container_name: bodgeit
    ports:
      - 8080:8080

  # OWASP Juice Shop as a target app
  # juiceshop:
  #   image: bkimminich/juice-shop:latest
  #   container_name: juice-shop
  #   ports:
  #     - 8082:3000

  # Pentest Insights application
  pentest-insights:
    build: .
    image: pentest-insights:2.0
    container_name: pentest-ins
    depends_on:
      - selenium-hub
      - chrome
      - firefox
      - zap
      - web-dvwa
      - bodgeit
#      - juiceshop
    ports:
      - 8000:8000 
    expose:
      - 8000
