version: '3.7'

services:
  db:
    image: mysql:8.0.19
    container_name: pi-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pi_schema
      MYSQL_USER: pi_admin
      MYSQL_PASSWORD: (e^g++|v6)$$
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - pi-network

  target:
    image: psiinon/bodgeit:latest
    container_name: bodgeit
    ports:
      - 8081:8080
    expose:
      - 8081
    networks:
      - pi-network

  zap-instance:
    image: owasp/zap2docker-stable:2.9.0
    command: zap.sh -daemon -port 8080 -host 127.0.0.1
    expose:
      # ZAP is running on 8080, we want it to be accessible by our tools
      - 8080
    networks:
      - pi-network

  pentest-insights:
    image: pentest-insights:0.1
    container_name: pentest-ins
    depends_on:
      - db
      - zap-instance
    ports:
      - 8000:8000
    expose:
      - 8000
    links:
      - db
      - zap-instance
    networks:
      - pi-network

networks:
  pi-network:
    driver: bridge